name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Update APT repository
      run: |
        sudo apt update
    
    - name: Get the LLVM installation script
      run: |
        wget https://apt.llvm.org/llvm.sh
    
    - name: Install latest LLVM
      run: |
        chmod +x llvm.sh; sudo ./llvm.sh all

    - name: Config the latest alternatives
      run: >
        sudo update-alternatives --install /bin/llvm-ml llvm-ml /bin/llvm-ml-17 0;
        sudo update-alternatives --install /bin/llvm-readobj llvm-readobj /bin/llvm-readobj-17 0;
        sudo update-alternatives --install /bin/clang-rename clang-rename /bin/clang-rename-17 0;
        sudo update-alternatives --install /bin/llvm-dwarfutil llvm-dwarfutil /bin/llvm-dwarfutil-17 0;
        sudo update-alternatives --install /bin/llvm-dwp llvm-dwp /bin/llvm-dwp-17 0;
        sudo update-alternatives --install /bin/UnicodeNameMappingGenerator UnicodeNameMappingGenerator /bin/UnicodeNameMappingGenerator-17 0;
        sudo update-alternatives --install /bin/count count /bin/count-17 0;
        sudo update-alternatives --install /bin/lldb lldb /bin/lldb-17 0;
        sudo update-alternatives --install /bin/llvm-rtdyld llvm-rtdyld /bin/llvm-rtdyld-17 0;
        sudo update-alternatives --install /bin/llc llc /bin/llc-17 0;
        sudo update-alternatives --install /bin/llvm-dwarfdump llvm-dwarfdump /bin/llvm-dwarfdump-17 0;
        sudo update-alternatives --install /bin/clang-include-fixer clang-include-fixer /bin/clang-include-fixer-17 0;
        sudo update-alternatives --install /bin/llvm-tli-checker llvm-tli-checker /bin/llvm-tli-checker-17 0;
        sudo update-alternatives --install /bin/split-file split-file /bin/split-file-17 0;
        sudo update-alternatives --install /bin/clang-apply-replacements clang-apply-replacements /bin/clang-apply-replacements-17 0;
        sudo update-alternatives --install /bin/llvm-strings llvm-strings /bin/llvm-strings-17 0;
        sudo update-alternatives --install /bin/amdgpu-arch amdgpu-arch /bin/amdgpu-arch-17 0;
        sudo update-alternatives --install /bin/llvm-ar llvm-ar /bin/llvm-ar-17 0;
        sudo update-alternatives --install /bin/clang-refactor clang-refactor /bin/clang-refactor-17 0;
        sudo update-alternatives --install /bin/llvm-link llvm-link /bin/llvm-link-17 0;
        sudo update-alternatives --install /bin/llvm-lipo llvm-lipo /bin/llvm-lipo-17 0;
        sudo update-alternatives --install /bin/clangd clangd /bin/clangd-17 0;
        sudo update-alternatives --install /bin/run-clang-tidy run-clang-tidy /bin/run-clang-tidy-17 0;
        sudo update-alternatives --install /bin/clang-include-cleaner clang-include-cleaner /bin/clang-include-cleaner-17 0;
        sudo update-alternatives --install /bin/llvm-strip llvm-strip /bin/llvm-strip-17 0;
        sudo update-alternatives --install /bin/llvm-cat llvm-cat /bin/llvm-cat-17 0;
        sudo update-alternatives --install /bin/llvm-profgen llvm-profgen /bin/llvm-profgen-17 0;
        sudo update-alternatives --install /bin/clang-scan-deps clang-scan-deps /bin/clang-scan-deps-17 0;
        sudo update-alternatives --install /bin/llvm-debuginfod llvm-debuginfod /bin/llvm-debuginfod-17 0;
        sudo update-alternatives --install /bin/yaml2obj yaml2obj /bin/yaml2obj-17 0;
        sudo update-alternatives --install /bin/llvm-omp-device-info llvm-omp-device-info /bin/llvm-omp-device-info-17 0;
        sudo update-alternatives --install /bin/verify-uselistorder verify-uselistorder /bin/verify-uselistorder-17 0;
        sudo update-alternatives --install /bin/FileCheck FileCheck /bin/FileCheck-17 0;
        sudo update-alternatives --install /bin/llvm-ifs llvm-ifs /bin/llvm-ifs-17 0;
        sudo update-alternatives --install /bin/lli-child-target lli-child-target /bin/lli-child-target-17 0;
        sudo update-alternatives --install /bin/llvm-cov llvm-cov /bin/llvm-cov-17 0;
        sudo update-alternatives --install /bin/clang-cpp clang-cpp /bin/clang-cpp-17 0;
        sudo update-alternatives --install /bin/llvm-objcopy llvm-objcopy /bin/llvm-objcopy-17 0;
        sudo update-alternatives --install /bin/llvm-tblgen llvm-tblgen /bin/llvm-tblgen-17 0;
        sudo update-alternatives --install /bin/ld64.lld ld64.lld ld64./bin/lld-17 0;
        sudo update-alternatives --install /bin/diagtool diagtool /bin/diagtool-17 0;
        sudo update-alternatives --install /bin/llvm-otool llvm-otool /bin/llvm-otool-17 0;
        sudo update-alternatives --install /bin/llvm-mca llvm-mca /bin/llvm-mca-17 0;
        sudo update-alternatives --install /bin/llvm-extract llvm-extract /bin/llvm-extract-17 0;
        sudo update-alternatives --install /bin/run-clang-tidy.py run-clang-tidy.py run-clang-tidy./bin/py-17 0;
        sudo update-alternatives --install /bin/llvm-cxxmap llvm-cxxmap /bin/llvm-cxxmap-17 0;
        sudo update-alternatives --install /bin/sancov sancov /bin/sancov-17 0;
        sudo update-alternatives --install /bin/clang-tblgen clang-tblgen /bin/clang-tblgen-17 0;
        sudo update-alternatives --install /bin/llvm-exegesis llvm-exegesis /bin/llvm-exegesis-17 0;
        sudo update-alternatives --install /bin/llvm-rc llvm-rc /bin/llvm-rc-17 0;
        sudo update-alternatives --install /bin/llvm-mc llvm-mc /bin/llvm-mc-17 0;
        sudo update-alternatives --install /bin/llvm-pdbutil llvm-pdbutil /bin/llvm-pdbutil-17 0;
        sudo update-alternatives --install /bin/llvm-cvtres llvm-cvtres /bin/llvm-cvtres-17 0;
        sudo update-alternatives --install /bin/llvm-opt-report llvm-opt-report /bin/llvm-opt-report-17 0;
        sudo update-alternatives --install /bin/opt opt /bin/opt-17 0;
        sudo update-alternatives --install /bin/llvm-dlltool llvm-dlltool /bin/llvm-dlltool-17 0;
        sudo update-alternatives --install /bin/llvm-remarkutil llvm-remarkutil /bin/llvm-remarkutil-17 0;
        sudo update-alternatives --install /bin/llvm-xray llvm-xray /bin/llvm-xray-17 0;
        sudo update-alternatives --install /bin/clang-offload-packager clang-offload-packager /bin/clang-offload-packager-17 0;
        sudo update-alternatives --install /bin/llvm-objdump llvm-objdump /bin/llvm-objdump-17 0;
        sudo update-alternatives --install /bin/llvm-omp-kernel-replay llvm-omp-kernel-replay /bin/llvm-omp-kernel-replay-17 0;
        sudo update-alternatives --install /bin/llvm-profdata llvm-profdata /bin/llvm-profdata-17 0;
        sudo update-alternatives --install /bin/llvm-gsymutil llvm-gsymutil /bin/llvm-gsymutil-17 0;
        sudo update-alternatives --install /bin/clang-move clang-move /bin/clang-move-17 0;
        sudo update-alternatives --install /bin/llvm-tapi-diff llvm-tapi-diff /bin/llvm-tapi-diff-17 0;
        sudo update-alternatives --install /bin/git-clang-format git-clang-format /bin/git-clang-format-17 0;
        sudo update-alternatives --install /bin/llvm-size llvm-size /bin/llvm-size-17 0;
        sudo update-alternatives --install /bin/dsymutil dsymutil /bin/dsymutil-17 0;
        sudo update-alternatives --install /bin/scan-build scan-build /bin/scan-build-17 0;
        sudo update-alternatives --install /bin/llvm-libtool-darwin llvm-libtool-darwin /bin/llvm-libtool-darwin-17 0;
        sudo update-alternatives --install /bin/llvm-lto llvm-lto /bin/llvm-lto-17 0;
        sudo update-alternatives --install /bin/clang-cl clang-cl /bin/clang-cl-17 0;
        sudo update-alternatives --install /bin/nvptx-arch nvptx-arch /bin/nvptx-arch-17 0;
        sudo update-alternatives --install /bin/llvm-modextract llvm-modextract /bin/llvm-modextract-17 0;
        sudo update-alternatives --install /bin/llvm-config llvm-config /bin/llvm-config-17 0;
        sudo update-alternatives --install /bin/lld lld /bin/lld-17 0;
        sudo update-alternatives --install /bin/intercept-build intercept-build /bin/intercept-build-17 0;
        sudo update-alternatives --install /bin/scan-view scan-view /bin/scan-view-17 0;
        sudo update-alternatives --install /bin/clang++ clang++ /bin/clang++-17 0;
        sudo update-alternatives --install /bin/llvm-debuginfo-analyzer llvm-debuginfo-analyzer /bin/llvm-debuginfo-analyzer-17 0;
        sudo update-alternatives --install /bin/llvm-install-name-tool llvm-install-name-tool /bin/llvm-install-name-tool-17 0;
        sudo update-alternatives --install /bin/llvm-stress llvm-stress /bin/llvm-stress-17 0;
        sudo update-alternatives --install /bin/analyze-build analyze-build /bin/analyze-build-17 0;
        sudo update-alternatives --install /bin/clang-linker-wrapper clang-linker-wrapper /bin/clang-linker-wrapper-17 0;
        sudo update-alternatives --install /bin/llvm-reduce llvm-reduce /bin/llvm-reduce-17 0;
        sudo update-alternatives --install /bin/llvm-bitcode-strip llvm-bitcode-strip /bin/llvm-bitcode-strip-17 0;
        sudo update-alternatives --install /bin/yaml-bench yaml-bench /bin/yaml-bench-17 0;
        sudo update-alternatives --install /bin/clang-check clang-check /bin/clang-check-17 0;
        sudo update-alternatives --install /bin/llvm-debuginfod-find llvm-debuginfod-find /bin/llvm-debuginfod-find-17 0;
        sudo update-alternatives --install /bin/scan-build-py scan-build-py /bin/scan-build-py-17 0;
        sudo update-alternatives --install /bin/llvm-symbolizer llvm-symbolizer /bin/llvm-symbolizer-17 0;
        sudo update-alternatives --install /bin/llvm-windres llvm-windres /bin/llvm-windres-17 0;
        sudo update-alternatives --install /bin/llvm-lto2 llvm-lto2 /bin/llvm-lto2-17 0;
        sudo update-alternatives --install /bin/clang-tidy clang-tidy /bin/clang-tidy-17 0;
        sudo update-alternatives --install /bin/llvm-cxxfilt llvm-cxxfilt /bin/llvm-cxxfilt-17 0;
        sudo update-alternatives --install /bin/lli lli /bin/lli-17 0;
        sudo update-alternatives --install /bin/obj2yaml obj2yaml /bin/obj2yaml-17 0;
        sudo update-alternatives --install /bin/llvm-PerfectShuffle llvm-PerfectShuffle /bin/llvm-PerfectShuffle-17 0;
        sudo update-alternatives --install /bin/llvm-jitlink-executor llvm-jitlink-executor /bin/llvm-jitlink-executor-17 0;
        sudo update-alternatives --install /bin/llvm-cxxdump llvm-cxxdump /bin/llvm-cxxdump-17 0;
        sudo update-alternatives --install /bin/clang-change-namespace clang-change-namespace /bin/clang-change-namespace-17 0;
        sudo update-alternatives --install /bin/llvm-split llvm-split /bin/llvm-split-17 0;
        sudo update-alternatives --install /bin/llvm-jitlink llvm-jitlink /bin/llvm-jitlink-17 0;
        sudo update-alternatives --install /bin/llvm-as llvm-as /bin/llvm-as-17 0;
        sudo update-alternatives --install /bin/find-all-symbols find-all-symbols /bin/find-all-symbols-17 0;
        sudo update-alternatives --install /bin/c-index-test c-index-test /bin/c-index-test-17 0;
        sudo update-alternatives --install /bin/bugpoint bugpoint /bin/bugpoint-17 0;
        sudo update-alternatives --install /bin/lldb-instr lldb-instr /bin/lldb-instr-17 0;
        sudo update-alternatives --install /bin/pp-trace pp-trace /bin/pp-trace-17 0;
        sudo update-alternatives --install /bin/modularize modularize /bin/modularize-17 0;
        sudo update-alternatives --install /bin/clang-doc clang-doc /bin/clang-doc-17 0;
        sudo update-alternatives --install /bin/clang-pseudo clang-pseudo /bin/clang-pseudo-17 0;
        sudo update-alternatives --install /bin/lldb-vscode lldb-vscode /bin/lldb-vscode-17 0;
        sudo update-alternatives --install /bin/clang-reorder-fields clang-reorder-fields /bin/clang-reorder-fields-17 0;
        sudo update-alternatives --install /bin/clang-tidy-diff.py clang-tidy-diff.py clang-tidy-diff./bin/py-17 0;
        sudo update-alternatives --install /bin/llvm-nm llvm-nm /bin/llvm-nm-17 0;
        sudo update-alternatives --install /bin/llvm-diff llvm-diff /bin/llvm-diff-17 0;
        sudo update-alternatives --install /bin/ld.lld ld.lld ld./bin/lld-17 0;
        sudo update-alternatives --install /bin/not not /bin/not-17 0;
        sudo update-alternatives --install /bin/clang-format-diff clang-format-diff /bin/clang-format-diff-17 0;
        sudo update-alternatives --install /bin/llvm-bcanalyzer llvm-bcanalyzer /bin/llvm-bcanalyzer-17 0;
        sudo update-alternatives --install /bin/llvm-readelf llvm-readelf /bin/llvm-readelf-17 0;
        sudo update-alternatives --install /bin/llvm-c-test llvm-c-test /bin/llvm-c-test-17 0;
        sudo update-alternatives --install /bin/clang-offload-bundler clang-offload-bundler /bin/clang-offload-bundler-17 0;
        sudo update-alternatives --install /bin/llvm-sim llvm-sim /bin/llvm-sim-17 0;
        sudo update-alternatives --install /bin/clang-query clang-query /bin/clang-query-17 0;
        sudo update-alternatives --install /bin/wasm-ld wasm-ld /bin/wasm-ld-17 0;
        sudo update-alternatives --install /bin/lldb-argdumper lldb-argdumper /bin/lldb-argdumper-17 0;
        sudo update-alternatives --install /bin/llvm-addr2line llvm-addr2line /bin/llvm-addr2line-17 0;
        sudo update-alternatives --install /bin/clang-format clang-format /bin/clang-format-17 0;
        sudo update-alternatives --install /bin/llvm-mt llvm-mt /bin/llvm-mt-17 0;
        sudo update-alternatives --install /bin/llvm-remark-size-diff llvm-remark-size-diff /bin/llvm-remark-size-diff-17 0;
        sudo update-alternatives --install /bin/clang-extdef-mapping clang-extdef-mapping /bin/clang-extdef-mapping-17 0;
        sudo update-alternatives --install /bin/clang-repl clang-repl /bin/clang-repl-17 0;
        sudo update-alternatives --install /bin/hmaptool hmaptool /bin/hmaptool-17 0;
        sudo update-alternatives --install /bin/llvm-undname llvm-undname /bin/llvm-undname-17 0;
        sudo update-alternatives --install /bin/llvm-dis llvm-dis /bin/llvm-dis-17 0;
        sudo update-alternatives --install /bin/sanstats sanstats /bin/sanstats-17 0;
        sudo update-alternatives --install /bin/lld-link lld-link /bin/lld-link-17 0;
        sudo update-alternatives --install /bin/lldb-server lldb-server /bin/lldb-server-17 0;
        sudo update-alternatives --install /bin/llvm-lib llvm-lib /bin/llvm-lib-17 0;
        sudo update-alternatives --install /bin/llvm-ranlib llvm-ranlib /bin/llvm-ranlib-17 0;
        sudo update-alternatives --install /bin/llvm-cfi-verify llvm-cfi-verify /bin/llvm-cfi-verify-17 0;
        sudo update-alternatives --install /bin/clang clang /bin/clang-17 0

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER="clang++"
        -DCMAKE_C_COMPILER="clang"
        -DCMAKE_BUILD_TYPE="Debug"
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config "Debug"

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config "Debug"